// Written by tools/gen-constants.py: FLTK's values of the constants
// TestConstants checks Fl's against. Edit the script, not this file.

#include <FL/Fl.H>
#include <FL/Enumerations.H>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

namespace {

struct Entry {
  const char *name;
  int32_t value;
};

const Entry entries[] = {
  {"FL_NO_EVENT", (int32_t)(FL_NO_EVENT)},
  {"FL_PUSH", (int32_t)(FL_PUSH)},
  {"FL_RELEASE", (int32_t)(FL_RELEASE)},
  {"FL_ENTER", (int32_t)(FL_ENTER)},
  {"FL_LEAVE", (int32_t)(FL_LEAVE)},
  {"FL_DRAG", (int32_t)(FL_DRAG)},
  {"FL_FOCUS", (int32_t)(FL_FOCUS)},
  {"FL_UNFOCUS", (int32_t)(FL_UNFOCUS)},
  {"FL_KEYDOWN", (int32_t)(FL_KEYDOWN)},
  {"FL_KEYUP", (int32_t)(FL_KEYUP)},
  {"FL_CLOSE", (int32_t)(FL_CLOSE)},
  {"FL_MOVE", (int32_t)(FL_MOVE)},
  {"FL_SHORTCUT", (int32_t)(FL_SHORTCUT)},
  {"FL_DEACTIVATE", (int32_t)(FL_DEACTIVATE)},
  {"FL_ACTIVATE", (int32_t)(FL_ACTIVATE)},
  {"FL_HIDE", (int32_t)(FL_HIDE)},
  {"FL_SHOW", (int32_t)(FL_SHOW)},
  {"FL_PASTE", (int32_t)(FL_PASTE)},
  {"FL_SELECTIONCLEAR", (int32_t)(FL_SELECTIONCLEAR)},
  {"FL_MOUSEWHEEL", (int32_t)(FL_MOUSEWHEEL)},
  {"FL_DND_ENTER", (int32_t)(FL_DND_ENTER)},
  {"FL_DND_DRAG", (int32_t)(FL_DND_DRAG)},
  {"FL_DND_LEAVE", (int32_t)(FL_DND_LEAVE)},
  {"FL_DND_RELEASE", (int32_t)(FL_DND_RELEASE)},
  {"FL_SCREEN_CONFIGURATION_CHANGED", (int32_t)(FL_SCREEN_CONFIGURATION_CHANGED)},
  {"FL_FULLSCREEN", (int32_t)(FL_FULLSCREEN)},
  {"FL_ZOOM_GESTURE", (int32_t)(FL_ZOOM_GESTURE)},
  {"FL_ZOOM_EVENT", (int32_t)(FL_ZOOM_EVENT)},
  {"FL_WHEN_NEVER", (int32_t)(FL_WHEN_NEVER)},
  {"FL_WHEN_CHANGED", (int32_t)(FL_WHEN_CHANGED)},
  {"FL_WHEN_NOT_CHANGED", (int32_t)(FL_WHEN_NOT_CHANGED)},
  {"FL_WHEN_RELEASE", (int32_t)(FL_WHEN_RELEASE)},
  {"FL_WHEN_RELEASE_ALWAYS", (int32_t)(FL_WHEN_RELEASE_ALWAYS)},
  {"FL_WHEN_ENTER_KEY", (int32_t)(FL_WHEN_ENTER_KEY)},
  {"FL_WHEN_ENTER_KEY_ALWAYS", (int32_t)(FL_WHEN_ENTER_KEY_ALWAYS)},
  {"FL_WHEN_ENTER_KEY_CHANGED", (int32_t)(FL_WHEN_ENTER_KEY_CHANGED)},
  {"FL_WHEN_CLOSED", (int32_t)(FL_WHEN_CLOSED)},
  {"FL_NO_BOX", (int32_t)(FL_NO_BOX)},
  {"FL_FLAT_BOX", (int32_t)(FL_FLAT_BOX)},
  {"FL_UP_BOX", (int32_t)(FL_UP_BOX)},
  {"FL_DOWN_BOX", (int32_t)(FL_DOWN_BOX)},
  {"FL_UP_FRAME", (int32_t)(FL_UP_FRAME)},
  {"FL_DOWN_FRAME", (int32_t)(FL_DOWN_FRAME)},
  {"FL_THIN_UP_BOX", (int32_t)(FL_THIN_UP_BOX)},
  {"FL_THIN_DOWN_BOX", (int32_t)(FL_THIN_DOWN_BOX)},
  {"FL_THIN_UP_FRAME", (int32_t)(FL_THIN_UP_FRAME)},
  {"FL_THIN_DOWN_FRAME", (int32_t)(FL_THIN_DOWN_FRAME)},
  {"FL_ENGRAVED_BOX", (int32_t)(FL_ENGRAVED_BOX)},
  {"FL_EMBOSSED_BOX", (int32_t)(FL_EMBOSSED_BOX)},
  {"FL_ENGRAVED_FRAME", (int32_t)(FL_ENGRAVED_FRAME)},
  {"FL_EMBOSSED_FRAME", (int32_t)(FL_EMBOSSED_FRAME)},
  {"FL_BORDER_BOX", (int32_t)(FL_BORDER_BOX)},
  {"FL_SHADOW_BOX", (int32_t)(FL_SHADOW_BOX)},
  {"FL_BORDER_FRAME", (int32_t)(FL_BORDER_FRAME)},
  {"FL_SHADOW_FRAME", (int32_t)(FL_SHADOW_FRAME)},
  {"FL_ROUNDED_BOX", (int32_t)(FL_ROUNDED_BOX)},
  {"FL_RSHADOW_BOX", (int32_t)(FL_RSHADOW_BOX)},
  {"FL_ROUNDED_FRAME", (int32_t)(FL_ROUNDED_FRAME)},
  {"FL_RFLAT_BOX", (int32_t)(FL_RFLAT_BOX)},
  {"FL_ROUND_UP_BOX", (int32_t)(FL_ROUND_UP_BOX)},
  {"FL_ROUND_DOWN_BOX", (int32_t)(FL_ROUND_DOWN_BOX)},
  {"FL_DIAMOND_UP_BOX", (int32_t)(FL_DIAMOND_UP_BOX)},
  {"FL_DIAMOND_DOWN_BOX", (int32_t)(FL_DIAMOND_DOWN_BOX)},
  {"FL_OVAL_BOX", (int32_t)(FL_OVAL_BOX)},
  {"FL_OSHADOW_BOX", (int32_t)(FL_OSHADOW_BOX)},
  {"FL_OVAL_FRAME", (int32_t)(FL_OVAL_FRAME)},
  {"FL_OFLAT_BOX", (int32_t)(FL_OFLAT_BOX)},
  {"FL_PLASTIC_UP_BOX", (int32_t)(FL_PLASTIC_UP_BOX)},
  {"FL_PLASTIC_DOWN_BOX", (int32_t)(FL_PLASTIC_DOWN_BOX)},
  {"FL_PLASTIC_UP_FRAME", (int32_t)(FL_PLASTIC_UP_FRAME)},
  {"FL_PLASTIC_DOWN_FRAME", (int32_t)(FL_PLASTIC_DOWN_FRAME)},
  {"FL_PLASTIC_THIN_UP_BOX", (int32_t)(FL_PLASTIC_THIN_UP_BOX)},
  {"FL_PLASTIC_THIN_DOWN_BOX", (int32_t)(FL_PLASTIC_THIN_DOWN_BOX)},
  {"FL_PLASTIC_ROUND_UP_BOX", (int32_t)(FL_PLASTIC_ROUND_UP_BOX)},
  {"FL_PLASTIC_ROUND_DOWN_BOX", (int32_t)(FL_PLASTIC_ROUND_DOWN_BOX)},
  {"FL_GTK_UP_BOX", (int32_t)(FL_GTK_UP_BOX)},
  {"FL_GTK_DOWN_BOX", (int32_t)(FL_GTK_DOWN_BOX)},
  {"FL_GTK_UP_FRAME", (int32_t)(FL_GTK_UP_FRAME)},
  {"FL_GTK_DOWN_FRAME", (int32_t)(FL_GTK_DOWN_FRAME)},
  {"FL_GTK_THIN_UP_BOX", (int32_t)(FL_GTK_THIN_UP_BOX)},
  {"FL_GTK_THIN_DOWN_BOX", (int32_t)(FL_GTK_THIN_DOWN_BOX)},
  {"FL_GTK_THIN_UP_FRAME", (int32_t)(FL_GTK_THIN_UP_FRAME)},
  {"FL_GTK_THIN_DOWN_FRAME", (int32_t)(FL_GTK_THIN_DOWN_FRAME)},
  {"FL_GTK_ROUND_UP_BOX", (int32_t)(FL_GTK_ROUND_UP_BOX)},
  {"FL_GTK_ROUND_DOWN_BOX", (int32_t)(FL_GTK_ROUND_DOWN_BOX)},
  {"FL_GLEAM_UP_BOX", (int32_t)(FL_GLEAM_UP_BOX)},
  {"FL_GLEAM_DOWN_BOX", (int32_t)(FL_GLEAM_DOWN_BOX)},
  {"FL_GLEAM_UP_FRAME", (int32_t)(FL_GLEAM_UP_FRAME)},
  {"FL_GLEAM_DOWN_FRAME", (int32_t)(FL_GLEAM_DOWN_FRAME)},
  {"FL_GLEAM_THIN_UP_BOX", (int32_t)(FL_GLEAM_THIN_UP_BOX)},
  {"FL_GLEAM_THIN_DOWN_BOX", (int32_t)(FL_GLEAM_THIN_DOWN_BOX)},
  {"FL_GLEAM_ROUND_UP_BOX", (int32_t)(FL_GLEAM_ROUND_UP_BOX)},
  {"FL_GLEAM_ROUND_DOWN_BOX", (int32_t)(FL_GLEAM_ROUND_DOWN_BOX)},
  {"FL_OXY_UP_BOX", (int32_t)(FL_OXY_UP_BOX)},
  {"FL_OXY_DOWN_BOX", (int32_t)(FL_OXY_DOWN_BOX)},
  {"FL_OXY_UP_FRAME", (int32_t)(FL_OXY_UP_FRAME)},
  {"FL_OXY_DOWN_FRAME", (int32_t)(FL_OXY_DOWN_FRAME)},
  {"FL_OXY_THIN_UP_BOX", (int32_t)(FL_OXY_THIN_UP_BOX)},
  {"FL_OXY_THIN_DOWN_BOX", (int32_t)(FL_OXY_THIN_DOWN_BOX)},
  {"FL_OXY_THIN_UP_FRAME", (int32_t)(FL_OXY_THIN_UP_FRAME)},
  {"FL_OXY_THIN_DOWN_FRAME", (int32_t)(FL_OXY_THIN_DOWN_FRAME)},
  {"FL_OXY_ROUND_UP_BOX", (int32_t)(FL_OXY_ROUND_UP_BOX)},
  {"FL_OXY_ROUND_DOWN_BOX", (int32_t)(FL_OXY_ROUND_DOWN_BOX)},
  {"FL_OXY_BUTTON_UP_BOX", (int32_t)(FL_OXY_BUTTON_UP_BOX)},
  {"FL_OXY_BUTTON_DOWN_BOX", (int32_t)(FL_OXY_BUTTON_DOWN_BOX)},
  {"FL_FREE_BOXTYPE", (int32_t)(FL_FREE_BOXTYPE)},
  {"FL_NORMAL_LABEL", (int32_t)(FL_NORMAL_LABEL)},
  {"FL_NO_LABEL", (int32_t)(FL_NO_LABEL)},
  {"FL_SHADOW_LABEL", (int32_t)(FL_SHADOW_LABEL)},
  {"FL_ENGRAVED_LABEL", (int32_t)(FL_ENGRAVED_LABEL)},
  {"FL_EMBOSSED_LABEL", (int32_t)(FL_EMBOSSED_LABEL)},
  {"FL_ALIGN_CENTER", (int32_t)(FL_ALIGN_CENTER)},
  {"FL_ALIGN_TOP", (int32_t)(FL_ALIGN_TOP)},
  {"FL_ALIGN_BOTTOM", (int32_t)(FL_ALIGN_BOTTOM)},
  {"FL_ALIGN_LEFT", (int32_t)(FL_ALIGN_LEFT)},
  {"FL_ALIGN_RIGHT", (int32_t)(FL_ALIGN_RIGHT)},
  {"FL_ALIGN_INSIDE", (int32_t)(FL_ALIGN_INSIDE)},
  {"FL_ALIGN_TEXT_OVER_IMAGE", (int32_t)(FL_ALIGN_TEXT_OVER_IMAGE)},
  {"FL_ALIGN_IMAGE_OVER_TEXT", (int32_t)(FL_ALIGN_IMAGE_OVER_TEXT)},
  {"FL_ALIGN_CLIP", (int32_t)(FL_ALIGN_CLIP)},
  {"FL_ALIGN_WRAP", (int32_t)(FL_ALIGN_WRAP)},
  {"FL_ALIGN_IMAGE_NEXT_TO_TEXT", (int32_t)(FL_ALIGN_IMAGE_NEXT_TO_TEXT)},
  {"FL_ALIGN_TEXT_NEXT_TO_IMAGE", (int32_t)(FL_ALIGN_TEXT_NEXT_TO_IMAGE)},
  {"FL_ALIGN_IMAGE_BACKDROP", (int32_t)(FL_ALIGN_IMAGE_BACKDROP)},
  {"FL_ALIGN_TOP_LEFT", (int32_t)(FL_ALIGN_TOP_LEFT)},
  {"FL_ALIGN_TOP_RIGHT", (int32_t)(FL_ALIGN_TOP_RIGHT)},
  {"FL_ALIGN_BOTTOM_LEFT", (int32_t)(FL_ALIGN_BOTTOM_LEFT)},
  {"FL_ALIGN_BOTTOM_RIGHT", (int32_t)(FL_ALIGN_BOTTOM_RIGHT)},
  {"FL_ALIGN_LEFT_TOP", (int32_t)(FL_ALIGN_LEFT_TOP)},
  {"FL_ALIGN_RIGHT_TOP", (int32_t)(FL_ALIGN_RIGHT_TOP)},
  {"FL_ALIGN_LEFT_BOTTOM", (int32_t)(FL_ALIGN_LEFT_BOTTOM)},
  {"FL_ALIGN_RIGHT_BOTTOM", (int32_t)(FL_ALIGN_RIGHT_BOTTOM)},
  {"FL_ALIGN_NOWRAP", (int32_t)(FL_ALIGN_NOWRAP)},
  {"FL_ALIGN_POSITION_MASK", (int32_t)(FL_ALIGN_POSITION_MASK)},
  {"FL_ALIGN_IMAGE_MASK", (int32_t)(FL_ALIGN_IMAGE_MASK)},
  {"FL_HELVETICA", (int32_t)(FL_HELVETICA)},
  {"FL_HELVETICA_BOLD", (int32_t)(FL_HELVETICA_BOLD)},
  {"FL_HELVETICA_ITALIC", (int32_t)(FL_HELVETICA_ITALIC)},
  {"FL_HELVETICA_BOLD_ITALIC", (int32_t)(FL_HELVETICA_BOLD_ITALIC)},
  {"FL_COURIER", (int32_t)(FL_COURIER)},
  {"FL_COURIER_BOLD", (int32_t)(FL_COURIER_BOLD)},
  {"FL_COURIER_ITALIC", (int32_t)(FL_COURIER_ITALIC)},
  {"FL_COURIER_BOLD_ITALIC", (int32_t)(FL_COURIER_BOLD_ITALIC)},
  {"FL_TIMES", (int32_t)(FL_TIMES)},
  {"FL_TIMES_BOLD", (int32_t)(FL_TIMES_BOLD)},
  {"FL_TIMES_ITALIC", (int32_t)(FL_TIMES_ITALIC)},
  {"FL_TIMES_BOLD_ITALIC", (int32_t)(FL_TIMES_BOLD_ITALIC)},
  {"FL_SYMBOL", (int32_t)(FL_SYMBOL)},
  {"FL_SCREEN", (int32_t)(FL_SCREEN)},
  {"FL_SCREEN_BOLD", (int32_t)(FL_SCREEN_BOLD)},
  {"FL_ZAPF_DINGBATS", (int32_t)(FL_ZAPF_DINGBATS)},
  {"FL_FREE_FONT", (int32_t)(FL_FREE_FONT)},
  {"FL_BOLD", (int32_t)(FL_BOLD)},
  {"FL_ITALIC", (int32_t)(FL_ITALIC)},
  {"FL_BOLD_ITALIC", (int32_t)(FL_BOLD_ITALIC)},
  {"FL_FOREGROUND_COLOR", (int32_t)(FL_FOREGROUND_COLOR)},
  {"FL_BACKGROUND2_COLOR", (int32_t)(FL_BACKGROUND2_COLOR)},
  {"FL_INACTIVE_COLOR", (int32_t)(FL_INACTIVE_COLOR)},
  {"FL_SELECTION_COLOR", (int32_t)(FL_SELECTION_COLOR)},
  {"FL_GRAY0", (int32_t)(FL_GRAY0)},
  {"FL_DARK3", (int32_t)(FL_DARK3)},
  {"FL_DARK2", (int32_t)(FL_DARK2)},
  {"FL_DARK1", (int32_t)(FL_DARK1)},
  {"FL_BACKGROUND_COLOR", (int32_t)(FL_BACKGROUND_COLOR)},
  {"FL_LIGHT1", (int32_t)(FL_LIGHT1)},
  {"FL_LIGHT2", (int32_t)(FL_LIGHT2)},
  {"FL_LIGHT3", (int32_t)(FL_LIGHT3)},
  {"FL_GRAY", (int32_t)(FL_GRAY)},
  {"FL_BLACK", (int32_t)(FL_BLACK)},
  {"FL_RED", (int32_t)(FL_RED)},
  {"FL_GREEN", (int32_t)(FL_GREEN)},
  {"FL_YELLOW", (int32_t)(FL_YELLOW)},
  {"FL_BLUE", (int32_t)(FL_BLUE)},
  {"FL_MAGENTA", (int32_t)(FL_MAGENTA)},
  {"FL_CYAN", (int32_t)(FL_CYAN)},
  {"FL_DARK_RED", (int32_t)(FL_DARK_RED)},
  {"FL_DARK_GREEN", (int32_t)(FL_DARK_GREEN)},
  {"FL_DARK_YELLOW", (int32_t)(FL_DARK_YELLOW)},
  {"FL_DARK_BLUE", (int32_t)(FL_DARK_BLUE)},
  {"FL_DARK_MAGENTA", (int32_t)(FL_DARK_MAGENTA)},
  {"FL_DARK_CYAN", (int32_t)(FL_DARK_CYAN)},
  {"FL_WHITE", (int32_t)(FL_WHITE)},
  {"FL_FREE_COLOR", (int32_t)(FL_FREE_COLOR)},
  {"FL_NUM_FREE_COLOR", (int32_t)(FL_NUM_FREE_COLOR)},
  {"FL_NUM_GRAY", (int32_t)(FL_NUM_GRAY)},
  {"FL_NUM_RED", (int32_t)(FL_NUM_RED)},
  {"FL_NUM_GREEN", (int32_t)(FL_NUM_GREEN)},
  {"FL_NUM_BLUE", (int32_t)(FL_NUM_BLUE)},
  {"fl_gray_ramp(0)", (int32_t)(fl_gray_ramp(0))},
  {"fl_gray_ramp(23)", (int32_t)(fl_gray_ramp(23))},
  {"fl_color_cube(0, 0, 0)", (int32_t)(fl_color_cube(0, 0, 0))},
  {"fl_color_cube(4, 7, 4)", (int32_t)(fl_color_cube(4, 7, 4))},
  {"fl_color_cube(1, 2, 3)", (int32_t)(fl_color_cube(1, 2, 3))},
  {"fl_rgb_color(255, 0, 0)", (int32_t)(fl_rgb_color(255, 0, 0))},
  {"fl_rgb_color(1, 2, 3)", (int32_t)(fl_rgb_color(1, 2, 3))},
  {"fl_rgb_color(0, 0, 255)", (int32_t)(fl_rgb_color(0, 0, 255))}
};

}  // namespace

extern "C" {

// The value of the C expression name, in *value; 0 if the table hasn't it.
int32_t ofltest_constant(const char *name, int32_t *value) {
  for (const Entry &e : entries) {
    if (strcmp(e.name, name) == 0) {
      *value = e.value;
      return 1;
    }
  }
  return 0;
}

}  // extern "C"
